-- AlterTable
ALTER TABLE "Active" ADD COLUMN     "endAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "startAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "GroupMember" ADD COLUMN     "nickname" TEXT;
